language: php

sudo: false

matrix:
    include:
        - php: hhvm
        - php: 5.5
        - php: 5.6
        - php: nightly
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update

install:
    - composer --prefer-source install

script:
    - composer validate
    - ./vendor/bin/phpcs --standard=PSR2 src
    - ./vendor/bin/phpunit --coverage-text --verbose

notifications:
    slack: monii:XmxGEoN5la6724Zjon4z9FeW
